# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
!pip install mdutils

  Using cached mdutils-1.2.1.tar.gz (17 kB)
  Created wheel for mdutils: filename=mdutils-1.2.1-py3-none-any.whl size=19324 sha256=6fddf4caaa850a121a116ffbe3c957a6d6e23d668e8204195c2a96c511f77df9
  Stored in directory: /Users/chanya/Library/Caches/pip/wheels/b5/5f/2b/8c4ea034f5bd832c2327ee0e014a21e586e637599bf5084bb3
Successfully built mdutils


In [110]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [111]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/chanya/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/chanya/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/chanya/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/chanya/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/chanya/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/chanya/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/chanya/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/chanya/opt/anaconda3/include']
None


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [7]:
x = np.zeros(10)
x.nbytes

80

In [9]:
Z = np.zeros(10)
print("%d bytes" % (Z.size * Z.itemsize))

80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [14]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [21]:
%run -c "import numpy; numpy.info(numpy.add)"

UsageError: option -c not recognized ( allowed: "nidtN:b:pD:l:rs:T:em:G" )


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [22]:
x = np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [25]:
x = np.array([i for i in range(10,50)])
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [26]:
answer(7)

Z = np.arange(10,50)
print(Z)


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [29]:
x = np.arange(1,10)
y = x[::-1]
y

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [30]:
answer(8)

Z = np.arange(50)
Z = Z[::-1]
print(Z)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [33]:
x = np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [36]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [45]:
np.random.random((3,3,3))

array([[[0.85424137, 0.15478408, 0.00948286],
        [0.40172839, 0.26904555, 0.30609924],
        [0.66650544, 0.98222006, 0.55809595]],

       [[0.45581105, 0.88957109, 0.65609252],
        [0.6220283 , 0.26146396, 0.95999995],
        [0.5934759 , 0.45362339, 0.61937127]],

       [[0.97444129, 0.15542968, 0.91959429],
        [0.99311237, 0.5673482 , 0.21172479],
        [0.01277246, 0.35633811, 0.85794204]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [50]:
z = np.random.random((10,10))
print(z.min(),z.max())


0.0005506993492482293 0.9720109395554289


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [51]:
z = np.random.random(30)
z.mean()

0.47006372511366146

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [59]:
z = np.ones((5,5))
z[1:-1,1:-1] =0 
z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [65]:
z = np.ones((5,5))
np.pad(z,1)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [82]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [87]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [98]:
z = np.zeros((8,8))
z[1::2,::2] = 1
z[::2,1::2] = 1
z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [102]:
(x,y,z)=(1,5,3)

In [103]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [17]:
np.tile( np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
z = np.random.random((5,5))
z - z.mean()/z.std()

array([[-1.6979436 , -1.88396824, -1.28350439, -1.17409417, -1.29852756],
       [-1.36028262, -1.76512848, -1.24831304, -1.3566554 , -1.24092573],
       [-1.29083293, -1.73425888, -1.41171858, -1.65310246, -1.67329269],
       [-1.4408761 , -1.07769181, -1.13198656, -1.93580331, -1.68508094],
       [-1.403566  , -1.25937184, -1.89632662, -1.12698432, -1.16544226]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [27]:
answer(23)

color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [34]:
x = np.ones((5,3))
y = np.ones((3,2))
np.dot(x,y)

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [40]:
a = np.arange(11)
a[(3<=a)&(a<=8)] *=-1
a

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

https://stackoverflow.com/questions/42955201/python-numpy-range-and-sum-1

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [80]:
Z = np.eye(4)
Z

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [83]:
x = np.random.random(5)
np.ceil(x)

array([1., 1., 1., 1., 1.])

In [91]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ -6.  -9.   2.  -4.   5.   6. -10. -10.   8.  -1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [93]:
x = np.array([1,2,3,4,5])
y = np.array([3,4,5,6,7,8])
np.intersect1d(x,y)

array([3, 4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [96]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [98]:
np.emath.sqrt(-1)

1j

np.emath.sqrt() は引数が負の実数の場合にも、複素数を返す。

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [106]:
np.datetime64('today')-np.timedelta64(1)

numpy.datetime64('2020-05-25')

In [107]:
np.datetime64('today')

numpy.datetime64('2020-05-26')

In [108]:
np.datetime64('today')+np.timedelta64(1)

numpy.datetime64('2020-05-27')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [112]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [115]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [119]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[8. 7. 9. 0. 5. 6. 5. 0. 6. 5.]
[8. 7. 9. 0. 5. 6. 5. 0. 6. 5.]
[8. 7. 9. 0. 5. 6. 5. 0. 6. 5.]
[8 7 9 0 5 6 5 0 6 5]
[8. 7. 9. 0. 5. 6. 5. 0. 6. 5.]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [127]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [131]:
np.linspace(0, 1, 11,endpoint=False)

TypeError: _linspace_dispatcher() got multiple values for argument 'start'

In [132]:
answer(39)

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [9]:
x = np.random.random(10)
s = np.sort(x)
print(s)

[0.01111572 0.06012844 0.08377676 0.13802005 0.21285419 0.42930314
 0.48716809 0.64887686 0.76234543 0.76330535]


In [12]:
answer(40)

Z = np.random.random(10)
Z.sort()
print(Z)


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [18]:
x = np.ones((10))
np.add.reduce(x)

10.0

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [25]:
a = np.ones((10))
b = np.ones((10))
np.array_equal(a,b)

True

In [26]:
answer(42)

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)


#### 43. Make an array immutable (read-only) (★★☆)

In [30]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [33]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.93928188 0.78238667 0.13654552 0.85893412 0.71067211 0.6695382
 0.65353893 1.06692952 0.95667139 0.64211793]
[0.74765572 0.74272965 1.54479964 1.46557818 0.37743492 1.12064109
 1.47700603 0.5964467  0.74799044 0.78057718]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [39]:
Z = np.random.random((10))
Z[Z.argmax()]=0
Z

array([0.76605512, 0.51175533, 0.25887591, 0.86435484, 0.42416152,
       0.19524422, 0.57558605, 0.        , 0.69201998, 0.81336141])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [75]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [70]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [61]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [53]:
np.set_printoptions(100)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [49]:
answer(49)

np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [83]:
Z=np.arange(10)
x =2.4
Z[np.abs(Z-x).argmin()]

2

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [90]:
Z = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [93]:
Z['position']['x']

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [109]:
Z = np.random.random((100,2))
hint(52)

hint: np.atleast_2d, T, np.sqrt


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [107]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Z)
print(Y)

[7.15e-44 1.30e-43 5.89e-44 1.14e-43 1.26e-44 3.22e-44 6.87e-44 0.00e+00
 8.55e-44 2.52e-44]
[51 93 42 81  9 23 49  0 61 18]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [114]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [118]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [121]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.3678794411714422 0.4482208784547898 0.5197948899339158 ...
  0.5197948899339159 0.4482208784547898 0.3678794411714422]
 [0.4482208784547898 0.5461081359780512 0.6333132437099518 ...
  0.6333132437099519 0.5461081359780512 0.4482208784547898]
 [0.5197948899339158 0.6333132437099518 0.7344436719297311 ...
  0.7344436719297313 0.6333132437099519 0.5197948899339158]
 ...
 [0.5197948899339159 0.6333132437099519 0.7344436719297313 ...
  0.7344436719297314 0.633313243709952  0.5197948899339159]
 [0.4482208784547898 0.5461081359780512 0.6333132437099519 ...
  0.633313243709952  0.5461081359780513 0.4482208784547898]
 [0.3678794411714422 0.4482208784547898 0.5197948899339158 ...
  0.5197948899339159 0.4482208784547898 0.3678794411714422]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [133]:
p=3
x = np.random.random((4,4))
np.put(x,np.random.choice(range(4*4), p, replace=False),1)
x

array([[0.47316177594549014 , 0.49103482076979565 , 0.3696473475278761  ,
        0.4405666998341339  ],
       [0.9490537504798539  , 0.8960266155957676  , 0.6772663819456745  ,
        1.                  ],
       [1.                  , 0.18373531685451805 , 0.3052082841951985  ,
        0.23092530001382683 ],
       [1.                  , 0.3938238434149236  , 0.8970972741953198  ,
        0.009773396492657627]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [138]:
x = np.random.random((4,4))
#collasp col so axis=1
y =x-x.mean(axis=1,keepdims=True)
y

array([[-0.23992017482552075 ,  0.020494334365946054,
        -0.19580255683449788 ,  0.41522839729407257 ],
       [-0.1850451529986304  ,  0.14586832257619115 ,
         0.18271745746305407 , -0.14354062704061493 ],
       [-0.14141083654408781 , -0.18655319438706008 ,
         0.5117787431333263  , -0.18381471220217838 ],
       [ 0.012552903858614184,  0.22662974075249687 ,
        -0.4246701718842604  ,  0.18548752727314954 ]])

#### 59. How to sort an array by the nth column? (★★☆)

In [142]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[3 1 7]
 [3 0 3]
 [0 7 8]]
[[3 0 3]
 [3 1 7]
 [0 7 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [147]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


In [148]:
Z

array([[1, 1, 0, ..., 2, 0, 2],
       [0, 1, 0, ..., 1, 2, 2],
       [1, 0, 0, ..., 2, 0, 0]])

#### 61. Find the nearest value from a given value in an array (★★☆)

In [151]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.668431254638627


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [165]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [168]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [171]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[1. 5. 3. 2. 2. 3. 6. 2. 1. 5.]
[ 1.  9.  5.  3.  3.  5. 11.  3.  1.  9.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [177]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


### working of numpy.bincount() method 
  
import numpy as geek 
  
### 1D array with +ve integers 
array2 = [10, 11, 4, 6, 2, 1, 9] 
array1 = [1, 3, 1, 3, 1, 2, 2] 
  
## array2 : weight 
bin = geek.bincount(array1, array2) 
print("Summation element-wise : \n", bin) 
  
#index 0 : 0 
#index 1 : 10 + 4 + 2 = 16 
#index 2 : 1 + 9 = 10 
#index 3 : 11 + 6 = 17 

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [185]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

4


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [189]:
x = np.random.randint(0,10,(3,3,3,3))
x.sum(axis=(-2,-1))

A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [197]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.4973113257838177  0.4839185476796974  0.4076525563063289
 0.4421664534464299  0.452461826760019   0.41520971052293026
 0.5657573297651418  0.4938386973057995  0.5969460138349524
 0.5779649944228695 ]


#### 69. How to get the diagonal of a dot product? (★★★)

In [194]:
x = np.random.randint(0,10,(3,3))
y = np.random.randint(0,10,(3,3))
np.diag(np.dot(x,y))

array([24, 87, 80])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [202]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. ... 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [207]:
x = np.random.randint(0,10,(5,5,3))
y = np.random.randint(0,10,(5,5))
x*y[:, :, None]


array([[[20, 15, 15],
        [ 0, 24, 24],
        [42, 36, 24],
        [54, 42, 36],
        [14,  8,  0]],

       [[28, 12, 36],
        [42,  6, 36],
        [36, 32, 36],
        [ 0,  4,  4],
        [48, 64, 32]],

       [[ 0, 36, 18],
        [42, 49, 14],
        [18, 36, 54],
        [56, 72, 40],
        [36, 12, 48]],

       [[ 0,  0,  0],
        [ 0, 27, 63],
        [ 4,  7,  0],
        [36, 32,  4],
        [ 5,  6,  9]],

       [[56,  0, 21],
        [ 0, 42, 35],
        [56, 24, 24],
        [18, 36,  6],
        [ 1,  7,  0]]])

#### 72. How to swap two rows of an array? (★★★)

In [212]:
x = np.random.randint(0,10,(3,3))
print(x)
x[[0,1]] = x[[1,0]]
print(x)

[[1 8 2]
 [3 5 9]
 [5 3 0]]
[[3 5 9]
 [1 8 2]
 [5 3 0]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [399]:
answer(73)

# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [231]:
C = np.arange(5)
A = np.repeat(np.arange(len(C)),C)
A

array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [223]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3. ... 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [404]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 ...
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [241]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.22730148152204332, -0.4222543857501262 ,  0.8807706519717005 ,
       ..., -0.5391391610417546 ,  0.40438648792345977,
       -0.14061254118614652])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [409]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 4.445763896116641    6.607233674409168    0.6703035587492093
 10.900884776977918    4.192712975910597    0.2758814472303742
  2.7658937852312215   0.13104559164493032  4.018112413128276
  0.16879567350260127]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [412]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 1.8121239915654068   1.8881472160793835   7.451874180213339   ...
   6.016056389329729    2.847426001701972    0.171763432282998  ]
 [10.116435704251286    7.129482553035505    3.944901602835997   ...
   2.901574298247888    1.1243002860404232   9.298237868732253  ]
 [ 6.963825145915059    2.7744200284755625   9.07854907998912    ...
   1.2314810767865088   4.190982162983158    4.628815824210447  ]
 ...
 [ 7.784931017135246    4.57680730311358     5.014813287826687   ...
   0.3811034486075201   0.07621148634700993  6.7088782573486325 ]
 [ 6.745917712968783   10.763438546320614    9.360605954953664   ...
  14.870840457344563    5.232780164882989    8.693235401839855  ]
 [ 3.9313926872243417   1.1115372000690837   3.7066618556206072  ...
   3.1798532661783376   1.0202884305251694   3.403897654060475  ]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [260]:
answer(80)

# Author: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [256]:
Z = np.arange(1,15,dtype=np.uint32)
R = np.lib.stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 ...
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [247]:
x = np.eye(3)
U,S,V = np.linalg.svd(x)
rank = np.sum(S > 1e-10)
rank

3

#### 83. How to find the most frequent value in an array?

In [267]:
x = np.array([1,2,3,1,5,2,4,5,1,2,1,1])
(np.bincount(x)).argmax()

Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [415]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 1 1]
   [3 0 4]
   [2 3 0]]

  [[1 1 3]
   [0 4 2]
   [3 0 0]]

  [[1 3 4]
   [4 2 1]
   [0 0 1]]

  ...

  [[4 3 2]
   [2 3 0]
   [3 4 3]]

  [[3 2 4]
   [3 0 0]
   [4 3 2]]

  [[2 4 3]
   [0 0 0]
   [3 2 4]]]


 [[[3 0 4]
   [2 3 0]
   [3 4 3]]

  [[0 4 2]
   [3 0 0]
   [4 3 2]]

  [[4 2 1]
   [0 0 1]
   [3 2 0]]

  ...

  [[2 3 0]
   [3 4 3]
   [4 4 3]]

  [[3 0 0]
   [4 3 2]
   [4 3 4]]

  [[0 0 0]
   [3 2 4]
   [3 4 4]]]


 [[[2 3 0]
   [3 4 3]
   [0 3 4]]

  [[3 0 0]
   [4 3 2]
   [3 4 4]]

  [[0 0 1]
   [3 2 0]
   [4 4 1]]

  ...

  [[3 4 3]
   [4 4 3]
   [4 0 3]]

  [[4 3 2]
   [4 3 4]
   [0 3 0]]

  [[3 2 4]
   [3 4 4]
   [3 0 2]]]


 ...


 [[[1 3 2]
   [4 1 1]
   [3 3 0]]

  [[3 2 1]
   [1 1 1]
   [3 0 0]]

  [[2 1 2]
   [1 1 2]
   [0 0 3]]

  ...

  [[0 4 3]
   [3 1 2]
   [0 3 1]]

  [[4 3 0]
   [1 2 0]
   [3 1 4]]

  [[3 0 3]
   [2 0 4]
   [1 4 1]]]


 [[[4 1 1]
   [3 3 0]
   [0 4 2]]

  [[1 1 1]
   [3 0 0]
   [4 2 2]]

  [[1 1 2]
   [0 0 3]
   [2 2 3]]

  ...

  [[3

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [309]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 2 13  8 10 10]
 [13  7  7 14 12]
 [ 8  7  9 42 15]
 [10 14 42  7 15]
 [10 12 15 15  6]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [326]:
n=4
p=3
m = np.ones((p,n,n))
v = np.ones((p,n,1))
np.tensordot(m,v,axes=((0,2),(0,1)))

array([[12.],
       [12.],
       [12.],
       [12.]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [321]:
Z = np.ones((16,16))
k=4
np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),np.arange(0, Z.shape[1], k), axis=1)

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [271]:
answer(88)

# Author: Nicolas Rougier

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)


#### 89. How to get the n largest values of an array (★★★)

In [285]:
a = np.array([9, 4, 4, 3, 3, 9, 0, 4, 6, 0])
ind = np.argpartition(a, -4)[-4:]
a[ind]

array([4, 9, 6, 9])

In [282]:
answer(89)

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [398]:
answer(90)

# Author: Stefan Van der Walt

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))


#### 91. How to create a record array from a regular array? (★★★)

In [289]:
answer(91)

Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [348]:
hint(92)
Z = np.random.randint(0,3,(20))
print(np.power(Z,3))
print(Z*Z*Z)
print(np.einsum('i,i,i->i',Z,Z,Z))

hint: np.power, *, np.einsum
[8 1 1 ... 1 0 8]
[8 1 1 ... 1 0 8]
[8 1 1 ... 1 0 8]


In [349]:
%timeit np.power(Z,3)
%timeit Z*Z*Z
%timeit np.einsum('i,i,i->i',Z,Z,Z)

946 ns ± 72.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
949 ns ± 83.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
2.48 µs ± 157 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [356]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 3 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [296]:
z = np.random.randint(0,3,(10,3))
E = np.all(z[:,1:] == z[:,:-1], axis=1)
U = z[~E]
U

array([[2, 1, 0],
       [1, 1, 0],
       [0, 0, 1],
       ...,
       [2, 0, 0],
       [0, 2, 1],
       [1, 1, 2]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [304]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [372]:
Z = np.random.randint(0,2,(6,3))
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [340]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
#inner
print(np.einsum("i,i",A,B))
#outer
print(np.einsum("i,j->ij",A,B))
#sum
print(np.einsum("i->",A))
#mul
print(np.einsum("i,i->i",A,B))

2.5878753229658784
[[0.04928211439482267  0.6411538739612712   0.7515832330467915   ...
  0.38489768360355303  0.07904350091119333  0.48402291584080004 ]
 [0.012147334869872012 0.1580352406905146   0.18525449499300617  ...
  0.0948717625204325   0.01948309009558586  0.11930471156951326 ]
 [0.033245874157584974 0.43252448218016887  0.5070204858631127   ...
  0.2596532253083279   0.053323001996532796 0.32652342836818504 ]
 ...
 [0.021359828575573385 0.2778885810105635   0.3257508168083228   ...
  0.16682215529638209  0.03425899335304571  0.20978496227213006 ]
 [0.013652833034567055 0.17762157525405795  0.20821428865978078  ...
  0.10662983668945392  0.021897756085756406 0.13409091992150762 ]
 [0.03789363885240487  0.4929912940436075   0.5779018199671634   ...
  0.2959526797237514   0.060777544022607134 0.3721713200496545  ]]
5.447567646765469
[0.04928211439482267  0.1580352406905146   0.5070204858631127
 0.7982787101614229   0.21013939151414904  0.16892690695848214
 0.1353012419515813   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [392]:
answer(98)

# Author: Bas Swinckels

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [379]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
print(M)
M &= (X.sum(axis=-1) == n)
print(X[M])

[ True  True False]
[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [388]:
X = np.random.randn(100)
N=1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.17157592246259093  0.19990571490991568]
